services:
  adwebapp:
    container_name: adwebapp
    build:
      context: ./
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    networks:
      - adwebapp-network

networks:
  adwebapp-network:
    driver: bridge
